name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  dockerlint:
    name: Dockerlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: hadolint/hadolint-action@v1.6.0
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: setup pyenv
        uses: gabrielfalcao/pyenv-action@v8
        env:
          # allow unsecure commands add-path and set-env until v7 is available
          # see: https://github.com/gabrielfalcao/pyenv-action/issues/99
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          default: 3.10
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and lint
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run pylint pavlov_generator
