name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  dockerlint:
    name: Dockerlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: hadolint/hadolint-action@v1.6.0
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions.setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies and lint
        run: |
          pip install poetry
          poetry install
          poetry run pylint pavlov_generator
