name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  dockerlint:
    name: Dockerlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: hadolint/hadolint-action@v1.6.0
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: nzdjb/pylint-action@main
